# Configuration Options for Colored Signs
# Colored Signs made by SirBlobman
# Made for version ${bukkit.plugin.version}
options:
  # What character should be used for color codes?
  # Legacy Colors are in the format <code><color>
  # Valid colors are 0-9
  # Valid formats are K-O and R
  # Example: &2&lHello is "Hello" with dark green and bold
  #
  # Default: '&'
  color character: '&'

  # Should permissions be used instead of allowing everyone to color their signs?
  #
  # Default: false
  use permissions: false

  # Should a message be broadcasted when Colored Signs is enabled on the server?
  #
  # Default: true
  broadcast startup: true
  
  # Should hex color codes be enabled if your server is 1.16+?
  # Hex Colors on signs are in the following format: <code>#<hex>
  # Example: &#FF0000 is RGB 255, 0, 0 or full red
  #
  # Default: true
  use hex colors: true

  # Only enable this option if you want to see extra debug messages.
  # SirBlobman may ask you to enable this option if you need help or have an issue.
  #
  # Default: false
  debug: false

messages:
  not-player: "&cYou are not a player."
  invalid-coordinates: "&7{value}&c is not a valid coordinate set."
  not-sign: "&cThe block at that location is not a sign."
  invalid-line: "&cThe line must be between 1 and 4 (Not &7{value}&c)."
  successful-edit: "&aSuccessfully changed the sign."